[project]
name = "graphql-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.4",
    "graphene-sqlalchemy>=2.1.0",
    "graphene>=3.4.1",
    "sqlalchemy>=2.0.36",
    "uvicorn>=0.32.0",
]
